site_name: Fantasy High Private Wiki
site_url: https://aelyxiris.github.io/fantasyhigh
site_author: Vern
site_description: A wiki for our fantasy high campaign!

nav:

  - Home: index.md
  - Characters: characters.md
  - Groups: groups.md
  - Installation: install.md

theme:
  name: material
  palette:
    accent: indigo
  features:
    -  content.tooltips

markdown_extensions:
  - toc:
      toc_depth: 3
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption

extra_css:
  - stylesheets/extra.css
